libekb-p10: Make it possible to `devtool modify libekb-p10`
Running `devtool modify libekb-p10` on my laptop leads to the following
failure:

    ERROR: Command Error: 'sh -c 'PATCHFILE="ekb_SegFault_Fix.patch" git -c user.name="OpenEmbedded" -c user.email="oe.patch@oe" commit -F /tmp/tmpa4rf20c3 --author="Jayanth Othayoth <ojayanth@in.ibm.com>" --date="Fri, 8 Nov 2019 00:29:30 -0600"'' exited with 0  Output:
    On branch devtool
    Changes not staged for commit:
            modified:   ekb (modified content)

    no changes added to commit
    ERROR: Logfile of failure stored in: /home/andrew/src/openbmc/openbmc/build/tmp/work/armv7at2hf-vfp-openbmc-linux-gnueabi/libekb-p10/1.0+gitAUTOINC+c8fb4ec13b_9ed077356c-r1/devtooltmp-jzoui5x1/temp/log.do_patch.12434

Essentially the source tree can't be patched because `git am` fails due to an
unrecognised patch format (ekb_SegFault_Fix.patch), and bitbake resorts to some
`git commit`-based hackery. Except we can't successfully commit because the
working tree is dirty, and this is because ekb_SegFault_Fix.patch applies to
the ekb/ subdirectory, which is also a git repository.

To handle this, flatten the nested repositories into one by reworking the
unpack phase to perform bare clones of libekb and ekb, then manually unpacking
them both into a third, flattened git repository, then applying all patches
to the third repository. With this approach we can successfully use `devtool
modify libekb-p10`.

Change-Id: I36f12266b16ee9295464cb7bbc73c752007b8882
Signed-off-by: Andrew Jeffery <andrew@aj.id.au>